# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files C:/Users/Thomas/Desktop/bg.coe
add_files C:/Users/Thomas/Desktop/plane.coe
add_files C:/Users/Thomas/Desktop/bullet.coe
add_files C:/Users/Thomas/Desktop/enemy0.coe
add_files C:/Users/Thomas/Desktop/enemy1.coe
add_files C:/Users/Thomas/Desktop/enemy2.coe
add_files C:/Users/Thomas/Desktop/enemy3.coe
add_files C:/Users/Thomas/Desktop/enemy4.coe
add_files C:/Users/Thomas/Desktop/enemy5.coe
add_files C:/Users/Thomas/Desktop/enemy6.coe
add_files C:/Users/Thomas/Desktop/enemy7.coe
add_files C:/Users/Thomas/Desktop/enemy8.coe
add_files C:/Users/Thomas/Desktop/enemy9.coe
read_ip -quiet {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci}}]

read_ip -quiet {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}]

read_verilog -library xil_defaultlib {
  C:/Users/Thomas/Desktop/logicDesignLab/lab08/Ps2Interface.v
  C:/Users/Thomas/Desktop/logicDesignLab/lab08/OnePulse.v
  C:/Users/Thomas/Desktop/logicDesignLab/lab08/KeyboardCtrl.v
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.srcs/sources_1/new/mem_addr_gen.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.srcs/sources_1/new/bg_addr_gen.v}
  C:/Users/Thomas/Downloads/counter.v
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.srcs/sources_1/new/clk_10Hz.v}
  C:/Users/Thomas/Desktop/logicDesignLab/lab08/KeyboardDecoder.v
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.srcs/sources_1/new/nine_to_twe.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.srcs/sources_1/new/vga_controller.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.srcs/sources_1/new/clock_divisor.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.srcs/sources_1/new/layer_compare.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.srcs/sources_1/new/top.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.srcs/constrs_1/new/cc.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_00/proto_00.srcs/constrs_1/new/cc.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
