# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files C:/Users/Thomas/Desktop/bg2.coe
add_files C:/Users/Thomas/Desktop/explosion.coe
add_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/bullet_green.coe}}
add_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/myplane.coe}}
add_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/enemy_green.coe}}
add_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/enemy_purple.coe}}
add_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/enemy_red.coe}}
add_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/menu_3.coe}}
add_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/gameover_3.coe}}
add_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/bullet0.coe}}
add_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/bullet_red.coe}}
add_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/bullet_purple.coe}}
read_ip -quiet {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_11/blk_mem_gen_11.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_11/blk_mem_gen_11_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_11/blk_mem_gen_11.xci}}]

read_ip -quiet {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_10/blk_mem_gen_10.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_10/blk_mem_gen_10_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_10/blk_mem_gen_10.xci}}]

read_ip -quiet {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_9_1/blk_mem_gen_9.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_9_1/blk_mem_gen_9_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_9_1/blk_mem_gen_9.xci}}]

read_ip -quiet {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}]

read_ip -quiet {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_8/blk_mem_gen_8.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_8/blk_mem_gen_8_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_8/blk_mem_gen_8.xci}}]

read_ip -quiet {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_7/blk_mem_gen_7.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_7/blk_mem_gen_7_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_7/blk_mem_gen_7.xci}}]

read_ip -quiet {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_6/blk_mem_gen_6.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_6/blk_mem_gen_6_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_6/blk_mem_gen_6.xci}}]

read_ip -quiet {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5.xci}}]

read_ip -quiet {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci}}]

read_ip -quiet {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci}}]

read_ip -quiet {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci}}]

read_ip -quiet {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci}}]

read_verilog -library xil_defaultlib {
  C:/Users/Thomas/Desktop/logicDesignLab/lab08/Ps2Interface.v
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/counter_enemy_bullet.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/counter_bullet.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/hit_detector_for_plane.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/hit_time_counter.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/one_pulse.v}
  C:/Users/Thomas/Desktop/logicDesignLab/lab08/OnePulse.v
  C:/Users/Thomas/Desktop/logicDesignLab/lab08/KeyboardCtrl.v
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/permanent_en.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/hit_detector.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/fsm_for_hit_.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/explosion_latency.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/mem_addr_gen.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/enable.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/menu_addr_gen.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/the_grand_shift_pattern.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/the_grand_rgb_mux.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/process.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/enemy_bullet.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/shift_pattern_01.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/decoder.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/clk_1Hz.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/one_bullet_addr.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/object_phase_for_bullet.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/clk_5s.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/object_phase_for_plane.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/clk_200Hz.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/ssd_ctl.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/ssd.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/freq_div.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/hit_counter.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/vga_controller.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/shift_pattern.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/scroll_down.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/nine_to_twe.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/layer_compare.v}
  C:/Users/Thomas/Desktop/logicDesignLab/lab08/KeyboardDecoder.v
  C:/Users/Thomas/Downloads/counter.v
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/clock_divisor.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/clk_10Hz.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/clk_100Hz.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/bg_addr_gen.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/object_phase.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/object_phase_for_enemy_bullet.v}
  {C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/sources_1/new/top.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/constrs_1/new/cc.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Thomas/Desktop/logicDesignLab/final project/proto_01/proto_00.srcs/constrs_1/new/cc.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
